# Generated by Django 3.2.9 on 2021-12-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20211226_1107'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('size', models.TextField()),
                ('hddSupport', models.IntegerField(null=True)),
                ('radSupport', models.IntegerField(null=True)),
                ('radSize', models.TextField()),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('coolType', models.TextField()),
                ('wattpower', models.IntegerField()),
                ('rad', models.IntegerField(null=True)),
                ('fans', models.IntegerField()),
                ('sockets', models.TextField()),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('vendor', models.TextField()),
                ('socket', models.TextField()),
                ('support_sockets', models.TextField()),
                ('wattPower', models.IntegerField()),
                ('boxCooler', models.BooleanField()),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('wattpower', models.IntegerField()),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('socket', models.CharField(max_length=255)),
                ('sata_ports', models.IntegerField()),
                ('m2_ports', models.IntegerField()),
                ('memory_place', models.IntegerField()),
                ('memory_type', models.TextField()),
                ('size', models.TextField()),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('wattpower', models.IntegerField()),
                ('plus_type', models.IntegerField()),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('port', models.TextField()),
                ('size', models.TextField()),
                ('st_size', models.IntegerField()),
            ],
            bases=('store.product',),
        ),
    ]
