# Generated by Django 4.0 on 2021-12-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='support_sockets',
            new_name='support_socket',
        ),
    ]
