# Generated by Django 4.0 on 2021-12-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_support_sockets_cpu_support_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(max_length=255),
        ),
    ]
