# Generated by Django 4.0 on 2021-12-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cpu_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='support_socket',
            field=models.CharField(max_length=255),
        ),
    ]
