# Generated by Django 4.0 on 2021-12-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cpu_support_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='support_socket2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='support_socket3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='support_socket4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='support_socket5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='support_socket6',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
