# Generated by Django 4.0 on 2021-12-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cpu_support_socket2_cpu_support_socket3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
