# Generated by Django 4.0 on 2021-12-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_case_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='radSize',
            field=models.CharField(max_length=255),
        ),
    ]
