# Generated by Django 4.0 on 2021-12-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_case_radsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooler',
            name='sockets',
            field=models.CharField(max_length=255),
        ),
    ]
