# Generated by Django 4.0 on 2021-12-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cooler_cooltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooler',
            name='sockets2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='sockets3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='sockets4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='sockets5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooler',
            name='sockets6',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
