# Generated by Django 4.0 on 2021-12-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cooler_sockets2_cooler_sockets3_cooler_sockets4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='memory_type',
            field=models.CharField(max_length=255),
        ),
    ]
