# Generated by Django 4.0 on 2021-12-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_motherboard_memory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
