# Generated by Django 4.0 on 2021-12-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cpu_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='hddSupport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='radSupport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='sockets2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='sockets3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='sockets4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='sockets5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='sockets6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='support_socket2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='support_socket3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='support_socket4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='support_socket5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='support_socket6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
