# Generated by Django 4.0 on 2021-12-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_case_hddsupport_alter_case_radsupport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu',
            name='plus_type',
            field=models.CharField(max_length=255),
        ),
    ]
