# Generated by Django 4.0 on 2021-12-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
